// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using RecipeBook.Infrastructure.Database.Context.RecipeBook;

#nullable disable

namespace RecipeBook.Infrastructure.Migrations
{
    [DbContext(typeof(RecipeBookDbContext))]
    partial class RecipeBookDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("RecipeBook.Domain.Entities.Recipes.RecipeBookEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc")
                        .HasDefaultValueSql("timezone('utc', now())");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(256)
                        .IsUnicode(true)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("title");

                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.Property<Guid>("Uuid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("uuid")
                        .HasDefaultValueSql("uuidv4()");

                    b.HasKey("Id")
                        .HasName("pk_recipe_book_id");

                    b.HasIndex("UserId");

                    b.HasIndex("Uuid")
                        .IsUnique()
                        .HasDatabaseName("ix_recipe_book_uuid");

                    b.ToTable("recipe_book", (string)null);
                });

            modelBuilder.Entity("RecipeBook.Domain.Entities.Recipes.RecipeEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc")
                        .HasDefaultValueSql("timezone('utc', now())");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(512)
                        .IsUnicode(true)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("description");

                    b.Property<short>("EstimatedTime")
                        .HasColumnType("smallint")
                        .HasColumnName("estimated_time");

                    b.Property<byte[]>("Image")
                        .HasMaxLength(5242880)
                        .HasColumnType("bytea")
                        .HasColumnName("image");

                    b.Property<bool>("IsPrivate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasColumnName("is_private")
                        .HasDefaultValueSql("false");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .IsUnicode(true)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("name");

                    b.Property<int>("RecipeBookId")
                        .HasColumnType("integer");

                    b.HasKey("Id")
                        .HasName("pk_recipe_id");

                    b.HasIndex("RecipeBookId");

                    b.ToTable("recipe", (string)null);
                });

            modelBuilder.Entity("RecipeBook.Domain.Entities.Recipes.RecipeIngredientEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc")
                        .HasDefaultValueSql("timezone('utc', now())");

                    b.Property<string>("Description")
                        .HasMaxLength(512)
                        .IsUnicode(true)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("description");

                    b.Property<byte>("MeasurementType")
                        .HasColumnType("smallint")
                        .HasColumnName("measurement_type");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .IsUnicode(true)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("name");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer")
                        .HasColumnName("quantity");

                    b.Property<int>("RecipeId")
                        .HasColumnType("integer")
                        .HasColumnName("recipe_id");

                    b.HasKey("Id")
                        .HasName("pk_recipe_ingredient_id");

                    b.HasIndex("RecipeId");

                    b.ToTable("recipe_ingredient", (string)null);
                });

            modelBuilder.Entity("RecipeBook.Domain.Entities.Recipes.RecipeStepEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc")
                        .HasDefaultValueSql("timezone('utc', now())");

                    b.Property<int>("RecipeId")
                        .HasColumnType("integer")
                        .HasColumnName("recipe_id");

                    b.Property<string>("StepDirections")
                        .IsRequired()
                        .HasMaxLength(512)
                        .IsUnicode(true)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("step_directions");

                    b.HasKey("Id")
                        .HasName("pk_recipe_step_id");

                    b.HasIndex("RecipeId");

                    b.ToTable("recipe_step", (string)null);
                });

            modelBuilder.Entity("RecipeBook.Domain.Entities.Recipes.RecipeStepIngredientEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc")
                        .HasDefaultValueSql("timezone('utc', now())");

                    b.Property<int>("IngredientId")
                        .HasColumnType("integer")
                        .HasColumnName("ingredient_id");

                    b.Property<int>("RecipeId")
                        .HasColumnType("integer")
                        .HasColumnName("recipe_id");

                    b.Property<int>("RecipeStepId")
                        .HasColumnType("integer")
                        .HasColumnName("recipe_step_id");

                    b.HasKey("Id")
                        .HasName("pk_recipe_step_ingredient_id");

                    b.HasIndex("IngredientId");

                    b.HasIndex("RecipeId");

                    b.HasIndex("RecipeStepId");

                    b.ToTable("recipe_step_ingredient", (string)null);
                });

            modelBuilder.Entity("RecipeBook.Domain.Entities.Users.UserEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc")
                        .HasDefaultValueSql("timezone('utc', now())");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(312)
                        .HasColumnType("character varying(312)")
                        .HasColumnName("email");

                    b.Property<Guid?>("EmailConfirmationToken")
                        .HasColumnType("uuid")
                        .HasColumnName("email_confirmation_token");

                    b.Property<bool>("IsEmailConfirmed")
                        .HasColumnType("boolean")
                        .HasColumnName("is_email_confirmed");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("password");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(128)
                        .IsUnicode(true)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("user_name");

                    b.Property<Guid>("Uuid")
                        .HasColumnType("uuid")
                        .HasColumnName("uuid");

                    b.HasKey("Id")
                        .HasName("pk_user_id");

                    b.HasIndex("Uuid")
                        .IsUnique()
                        .HasDatabaseName("idx_user_uuid");

                    b.ToTable("user", (string)null);
                });

            modelBuilder.Entity("RecipeBook.Domain.Entities.Recipes.RecipeBookEntity", b =>
                {
                    b.HasOne("RecipeBook.Domain.Entities.Users.UserEntity", "User")
                        .WithMany("RecipeBooks")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_recipe_book");

                    b.Navigation("User");
                });

            modelBuilder.Entity("RecipeBook.Domain.Entities.Recipes.RecipeEntity", b =>
                {
                    b.HasOne("RecipeBook.Domain.Entities.Recipes.RecipeBookEntity", "RecipeBook")
                        .WithMany("Recipes")
                        .HasForeignKey("RecipeBookId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_recipe_book_recipe");

                    b.Navigation("RecipeBook");
                });

            modelBuilder.Entity("RecipeBook.Domain.Entities.Recipes.RecipeIngredientEntity", b =>
                {
                    b.HasOne("RecipeBook.Domain.Entities.Recipes.RecipeEntity", "Recipe")
                        .WithMany("RecipeIngredients")
                        .HasForeignKey("RecipeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_recipe_ingredient_recipe");

                    b.Navigation("Recipe");
                });

            modelBuilder.Entity("RecipeBook.Domain.Entities.Recipes.RecipeStepEntity", b =>
                {
                    b.HasOne("RecipeBook.Domain.Entities.Recipes.RecipeEntity", "Recipe")
                        .WithMany("RecipeSteps")
                        .HasForeignKey("RecipeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_recipe_step_recipe");

                    b.Navigation("Recipe");
                });

            modelBuilder.Entity("RecipeBook.Domain.Entities.Recipes.RecipeStepIngredientEntity", b =>
                {
                    b.HasOne("RecipeBook.Domain.Entities.Recipes.RecipeIngredientEntity", "Ingredient")
                        .WithMany()
                        .HasForeignKey("IngredientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RecipeBook.Domain.Entities.Recipes.RecipeEntity", "Recipe")
                        .WithMany()
                        .HasForeignKey("RecipeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RecipeBook.Domain.Entities.Recipes.RecipeStepEntity", "RecipeStep")
                        .WithMany("RecipeStepIngredients")
                        .HasForeignKey("RecipeStepId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_recipe_step_ingredient_recipe_step");

                    b.Navigation("Ingredient");

                    b.Navigation("Recipe");

                    b.Navigation("RecipeStep");
                });

            modelBuilder.Entity("RecipeBook.Domain.Entities.Recipes.RecipeBookEntity", b =>
                {
                    b.Navigation("Recipes");
                });

            modelBuilder.Entity("RecipeBook.Domain.Entities.Recipes.RecipeEntity", b =>
                {
                    b.Navigation("RecipeIngredients");

                    b.Navigation("RecipeSteps");
                });

            modelBuilder.Entity("RecipeBook.Domain.Entities.Recipes.RecipeStepEntity", b =>
                {
                    b.Navigation("RecipeStepIngredients");
                });

            modelBuilder.Entity("RecipeBook.Domain.Entities.Users.UserEntity", b =>
                {
                    b.Navigation("RecipeBooks");
                });
#pragma warning restore 612, 618
        }
    }
}
