<Project Sdk="Aspire.AppHost.Sdk/13.0.2">

    <PropertyGroup>
        <OutputType>Exe</OutputType>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <UserSecretsId>5cd057f3-8de2-4f60-9884-e4598b3798e9</UserSecretsId>
    </PropertyGroup>

    <ItemGroup>
      <PackageReference Include="Aspire.Hosting.PostgreSQL" Version="13.1.0" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\RecipeBook.Api\RecipeBook.Api.csproj" />
    </ItemGroup>

</Project>
